/**
 * Export Service Types
 * Defines interfaces for PDF and Excel document generation
 */

// ============================================================================
// EXPORT REQUEST TYPES
// ============================================================================

export type ExportFormat = 'pdf' | 'excel';
export type ExportDocumentType = 'quote_comparison' | 'rfq' | 'order' | 'invoice' | 'payout';

export interface ExportRequest {
  type: ExportDocumentType;
  format: ExportFormat;
  documentId?: string;
  documentIds?: string[];
  filters?: ExportFilters;
  options?: ExportOptions;
  branding?: BrandingConfig;
}

export interface ExportFilters {
  dateFrom?: Date;
  dateTo?: Date;
  status?: string[];
  sellerId?: string;
  buyerId?: string;
  minAmount?: number;
  maxAmount?: number;
}

export interface ExportOptions {
  includeScoring?: boolean;
  includeHighlights?: boolean;
  includeMetadata?: boolean;
  includeAuditTrail?: boolean;
  language?: 'en' | 'ar';
  currency?: string;
  timezone?: string;
  pageSize?: 'A4' | 'Letter';
  orientation?: 'portrait' | 'landscape';
}

// ============================================================================
// BRANDING CONFIGURATION
// ============================================================================

export interface BrandingConfig {
  companyName: string;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  footerText?: string;
  showWatermark?: boolean;
}

export const DEFAULT_BRANDING: BrandingConfig = {
  companyName: 'NABD Marketplace',
  primaryColor: '#2563eb',
  secondaryColor: '#1e40af',
  footerText: 'Generated by NABD Marketplace',
  showWatermark: false,
};

// ============================================================================
// EXPORT RESULT
// ============================================================================

export interface ExportResult {
  success: boolean;
  jobId: string;
  status: ExportJobStatus;
  fileUrl?: string;
  filePath?: string;
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
  expiresAt?: Date;
  error?: string;
}

export type ExportJobStatus =
  | 'queued'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'expired';

export interface ExportJob {
  id: string;
  userId: string;
  request: ExportRequest;
  status: ExportJobStatus;
  progress: number;
  filePath?: string;
  fileUrl?: string;
  error?: string;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  expiresAt?: Date;
}

// ============================================================================
// QUOTE COMPARISON EXPORT
// ============================================================================

export interface QuoteComparisonExportData {
  rfq: RFQExportData;
  quotes: QuoteExportData[];
  scoring: QuoteScoringData;
  recommendation: RecommendationData;
  generatedAt: Date;
  generatedBy: string;
}

export interface QuoteScoringData {
  weights: {
    price: number;
    delivery: number;
    quality: number;
    reliability: number;
  };
  normalizedScores: {
    quoteId: string;
    priceScore: number;
    deliveryScore: number;
    qualityScore: number;
    reliabilityScore: number;
    totalScore: number;
  }[];
}

export interface RecommendationData {
  bestOverall: string;
  bestPrice: string;
  bestDelivery: string;
  bestQuality: string;
  highlights: HighlightItem[];
  warnings: WarningItem[];
}

export interface HighlightItem {
  quoteId: string;
  type: 'price' | 'delivery' | 'quality' | 'reliability';
  message: string;
  value?: string | number;
}

export interface WarningItem {
  quoteId: string;
  type: 'risk' | 'delay' | 'quality' | 'compliance';
  severity: 'low' | 'medium' | 'high';
  message: string;
}

// ============================================================================
// RFQ EXPORT
// ============================================================================

export interface RFQExportData {
  id: string;
  rfqNumber: string;
  status: string;

  // Buyer info
  buyerCompany: string;
  buyerContact: string;
  buyerEmail: string;

  // Items
  items: RFQItemExportData[];

  // Requirements
  deliveryLocation: AddressExportData;
  preferredDeliveryDate?: Date;
  paymentTerms?: string;
  notes?: string;

  // Timing
  createdAt: Date;
  expiresAt: Date;
  quotesReceived: number;

  // Metadata
  tags?: string[];
  priority?: 'low' | 'medium' | 'high' | 'urgent';
}

export interface RFQItemExportData {
  lineNumber: number;
  sku?: string;
  name: string;
  description?: string;
  quantity: number;
  unit: string;
  targetPrice?: number;
  specifications?: Record<string, string>;
}

// ============================================================================
// QUOTE EXPORT
// ============================================================================

export interface QuoteExportData {
  id: string;
  quoteNumber: string;
  rfqId: string;
  status: string;

  // Seller info
  sellerCompany: string;
  sellerContact: string;
  sellerEmail: string;
  sellerRating?: number;
  sellerReliability?: string;

  // Pricing
  lineItems: QuoteLineItemExportData[];
  subtotal: number;
  taxes: number;
  shipping: number;
  discount?: number;
  total: number;
  currency: string;

  // Terms
  validUntil: Date;
  estimatedDelivery: Date;
  leadTimeDays: number;
  paymentTerms: string;
  warranty?: string;

  // Scoring (if included)
  score?: {
    total: number;
    breakdown: {
      price: number;
      delivery: number;
      quality: number;
      reliability: number;
    };
    rank: number;
    pros: string[];
    cons: string[];
  };

  // Notes
  notes?: string;
  termsAndConditions?: string;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

export interface QuoteLineItemExportData {
  lineNumber: number;
  rfqItemId: string;
  sku?: string;
  name: string;
  description?: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  total: number;
  leadTimeDays?: number;
  notes?: string;
}

// ============================================================================
// ORDER EXPORT
// ============================================================================

export interface OrderExportData {
  id: string;
  orderNumber: string;
  source: 'rfq' | 'direct_buy' | 'cart';
  sourceId?: string;
  status: string;

  // Parties
  buyer: PartyExportData;
  seller: PartyExportData;

  // Items
  items: OrderItemExportData[];

  // Pricing
  subtotal: number;
  taxes: number;
  taxRate?: number;
  shipping: number;
  discount?: number;
  total: number;
  currency: string;

  // Payment
  paymentStatus: string;
  paymentMethod?: string;
  paidAt?: Date;

  // Fulfillment
  fulfillmentStatus: string;
  shippingAddress: AddressExportData;
  billingAddress?: AddressExportData;
  trackingNumber?: string;
  carrier?: string;

  // Health (if included)
  health?: {
    status: 'on_track' | 'at_risk' | 'delayed' | 'critical';
    reason?: string;
    estimatedDelivery?: Date;
    actualDelivery?: Date;
    delayDays?: number;
  };

  // Timestamps
  createdAt: Date;
  confirmedAt?: Date;
  processedAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  cancelledAt?: Date;

  // Audit trail (if included)
  auditTrail?: AuditEvent[];
}

export interface OrderItemExportData {
  lineNumber: number;
  sku?: string;
  name: string;
  description?: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  total: number;
  fulfilledQuantity?: number;
}

export interface PartyExportData {
  id: string;
  companyName: string;
  contactName: string;
  email: string;
  phone?: string;
  taxId?: string;
}

export interface AddressExportData {
  line1: string;
  line2?: string;
  city: string;
  state?: string;
  postalCode?: string;
  country: string;
}

export interface AuditEvent {
  timestamp: Date;
  action: string;
  actor: string;
  details?: string;
}

// ============================================================================
// INVOICE EXPORT
// ============================================================================

export interface InvoiceExportData {
  id: string;
  invoiceNumber: string;
  orderId: string;
  orderNumber: string;
  status: string;

  // Parties
  seller: PartyExportData;
  buyer: PartyExportData;

  // Addresses
  billingAddress: AddressExportData;
  shippingAddress?: AddressExportData;

  // Line items
  items: InvoiceLineItemExportData[];

  // Amounts
  subtotal: number;
  taxRate: number;
  taxAmount: number;
  shipping: number;
  discount?: number;
  total: number;
  amountPaid: number;
  amountDue: number;
  currency: string;

  // Dates
  issuedAt: Date;
  dueAt: Date;
  paidAt?: Date;

  // Payment
  paymentTerms: string;
  paymentInstructions?: string;
  bankDetails?: BankDetailsExportData;

  // Notes
  notes?: string;
  termsAndConditions?: string;

  // Metadata
  reference?: string;
  poNumber?: string;
}

export interface InvoiceLineItemExportData {
  lineNumber: number;
  sku?: string;
  name: string;
  description?: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  taxRate?: number;
  taxAmount?: number;
  total: number;
}

export interface BankDetailsExportData {
  bankName: string;
  accountHolder: string;
  accountNumber?: string;
  iban?: string;
  swiftBic?: string;
  routingNumber?: string;
}

// ============================================================================
// PAYOUT EXPORT
// ============================================================================

export interface PayoutExportData {
  id: string;
  payoutNumber: string;
  sellerId: string;
  status: string;

  // Seller info
  seller: PartyExportData;

  // Period
  periodStart: Date;
  periodEnd: Date;

  // Amounts
  grossAmount: number;
  platformFee: number;
  platformFeeRate: number;
  processingFee: number;
  adjustments: number;
  netAmount: number;
  currency: string;

  // Included items
  lineItems: PayoutLineItemExportData[];
  orderCount: number;
  invoiceCount: number;

  // Bank details
  bankDetails: BankDetailsExportData;

  // Timing
  scheduledAt: Date;
  processedAt?: Date;
  settledAt?: Date;

  // Reference
  transactionRef?: string;
}

export interface PayoutLineItemExportData {
  orderId: string;
  orderNumber: string;
  invoiceId: string;
  invoiceNumber: string;
  grossAmount: number;
  platformFee: number;
  netAmount: number;
  paidAt: Date;
}

// ============================================================================
// TEMPLATE DEFINITIONS
// ============================================================================

export interface PDFTemplate {
  type: ExportDocumentType;
  version: string;

  // Page setup
  pageSize: 'A4' | 'Letter';
  orientation: 'portrait' | 'landscape';
  margins: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };

  // Header
  header: {
    height: number;
    showLogo: boolean;
    showTitle: boolean;
    showDocumentNumber: boolean;
    showDate: boolean;
  };

  // Footer
  footer: {
    height: number;
    showPageNumbers: boolean;
    showGeneratedBy: boolean;
    showTimestamp: boolean;
  };

  // Fonts
  fonts: {
    primary: string;
    secondary: string;
    sizes: {
      title: number;
      subtitle: number;
      heading: number;
      body: number;
      small: number;
    };
  };

  // Colors
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    textLight: string;
    border: string;
    background: string;
    success: string;
    warning: string;
    error: string;
  };

  // Table styles
  table: {
    headerBackground: string;
    headerTextColor: string;
    alternateRowBackground: string;
    borderColor: string;
    cellPadding: number;
  };
}

export interface ExcelTemplate {
  type: ExportDocumentType;
  version: string;

  // Sheets configuration
  sheets: ExcelSheetConfig[];

  // Styling
  styles: {
    headerFont: ExcelFontConfig;
    bodyFont: ExcelFontConfig;
    titleFont: ExcelFontConfig;
    headerFill: string;
    alternateFill: string;
    borderColor: string;
  };
}

export interface ExcelSheetConfig {
  name: string;
  columns: ExcelColumnConfig[];
  includeSubtotals?: boolean;
  includeTotals?: boolean;
  freezeHeader?: boolean;
  autoFilter?: boolean;
}

export interface ExcelColumnConfig {
  key: string;
  header: string;
  width: number;
  type: 'string' | 'number' | 'currency' | 'date' | 'percentage' | 'status';
  format?: string;
  alignment?: 'left' | 'center' | 'right';
}

export interface ExcelFontConfig {
  name: string;
  size: number;
  bold?: boolean;
  color?: string;
}
