import React, { createContext, useContext, useState, useEffect, useMemo, ReactNode } from 'react';
import { getThemeStyles, ThemeStyles, Theme, Language } from '../../../theme/portalColors';

type Direction = 'ltr' | 'rtl';

interface PortalContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;
  direction: Direction;
  t: (key: string) => string;
  styles: ThemeStyles;
  sidebarCollapsed: boolean;
  setSidebarCollapsed: (collapsed: boolean) => void;
  toggleSidebar: () => void;
  sidebarWidth: number;
  setSidebarWidth: (width: number) => void;
}

const PortalContext = createContext<PortalContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.signOut': 'Sign Out',
    'common.seller': 'Seller',
    'common.buyer': 'Buyer',
    'common.search': 'Search',
    'common.viewAll': 'View All',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.actions': 'Actions',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.new': 'New',
    'common.view': 'View',
    'common.track': 'Track',
    'common.details': 'Details',
    'common.confirm': 'Confirm',
    'common.ship': 'Ship',
    'common.quote': 'Quote',
    'common.suppliers': 'Suppliers',
    'common.products': 'Products',
    'common.onTimeDelivery': 'On-time Delivery',
    'common.units': 'units',
    'common.unit': 'unit',
    'common.days': 'days',

    // Seller Nav
    'seller.nav.home': 'Home',
    'seller.nav.listings': 'Listings',
    'seller.nav.rfqs': 'RFQ Inbox',
    'seller.nav.orders': 'Orders',
    'seller.nav.analytics': 'Analytics',
    'seller.nav.workspace': 'Workspace',
    'seller.nav.inventory': 'Inventory',
    'seller.nav.logistics': 'Logistics',
    'seller.nav.tracking': 'Live Tracking',
    'seller.nav.settings': 'Settings',
    'seller.nav.tests': 'Tests',

    // Seller Tests
    'seller.tests.title': 'Tests',
    'seller.tests.subtitle': 'Manage and track your certification tests',
    'seller.tests.testName': 'Test Name',
    'seller.tests.status': 'Status',
    'seller.tests.score': 'Score',
    'seller.tests.duration': 'Duration',
    'seller.tests.date': 'Date',
    'seller.tests.passed': 'Passed',
    'seller.tests.pending': 'Pending',
    'seller.tests.failed': 'Failed',

    // Seller Home
    'seller.home.title': 'Seller Dashboard',
    'seller.home.subtitle': 'Manage your listings, respond to RFQs, and grow your business',
    'seller.home.revenue': 'Revenue (MTD)',
    'seller.home.activeOrders': 'Active Orders',
    'seller.home.rfqsThisMonth': 'RFQs This Month',
    'seller.home.fromLastMonth': 'from last month',
    'seller.home.manageListings': 'Manage Listings',
    'seller.home.viewListings': 'View Listings',
    'seller.home.activeProducts': 'active products in your catalog',
    'seller.home.rfqInbox': 'RFQ Inbox',
    'seller.home.viewRfqs': 'View RFQs',
    'seller.home.newRequests': 'new requests awaiting response',

    // Seller Listings
    'seller.listings.title': 'Listings',
    'seller.listings.subtitle': 'Manage your product catalog',
    'seller.listings.addProduct': 'Add Product',
    'seller.listings.searchPlaceholder': 'Search by SKU, name, or manufacturer...',
    'seller.listings.allCategories': 'All Categories',
    'seller.listings.allStatus': 'All Status',
    'seller.listings.noListings': 'No listings yet',
    'seller.listings.noListingsDesc': 'Add your first product to start receiving quote requests',
    'seller.listings.sku': 'SKU',
    'seller.listings.productName': 'Product Name',
    'seller.listings.manufacturer': 'Manufacturer',
    'seller.listings.category': 'Category',
    'seller.listings.price': 'Price',
    'seller.listings.stock': 'Stock',
    'seller.listings.status': 'Status',
    'seller.listings.active': 'Active',
    'seller.listings.draft': 'Draft',
    'seller.listings.outOfStock': 'Out of Stock',
    // Listings Filter & Table
    'seller.listings.filters': 'Filters',
    'seller.listings.searchBySku': 'Search by name or SKU...',
    'seller.listings.allStock': 'All Stock',
    'seller.listings.allVisibility': 'All Visibility',
    'seller.listings.inStock': 'In Stock',
    'seller.listings.lowStock': 'Low Stock',
    'seller.listings.public': 'Public',
    'seller.listings.hidden': 'Hidden',
    'seller.listings.rfqOnly': 'RFQ Only',
    'seller.listings.sortBy': 'Sort by',
    'seller.listings.lastUpdated': 'Last Updated',
    'seller.listings.nameAZ': 'Name A-Z',
    'seller.listings.priceLowHigh': 'Price: Low to High',
    'seller.listings.priceHighLow': 'Price: High to Low',
    'seller.listings.stockLowHigh': 'Stock: Low to High',
    'seller.listings.stockHighLow': 'Stock: High to Low',
    'seller.listings.clearAll': 'Clear all',
    'seller.listings.selected': 'selected',
    'seller.listings.setActive': 'Set Active',
    'seller.listings.setDraft': 'Set Draft',
    'seller.listings.makePublic': 'Make Public',
    'seller.listings.makeHidden': 'Make Hidden',
    'seller.listings.total': 'Total',
    'seller.listings.showing': 'Showing',
    'seller.listings.of': 'of',
    'seller.listings.products': 'products',
    'seller.listings.noProductsMatch': 'No products match your filters',
    'seller.listings.tryAdjusting': 'Try adjusting your search or filter criteria',
    'seller.listings.noProductsYet': 'No products yet',
    'seller.listings.startBuilding': 'Start building your catalog by adding your first product',
    'seller.listings.addFirstProduct': 'Add your first product',
    'seller.listings.orders': 'orders',
    'seller.listings.rfqs': 'RFQs',
    'seller.listings.performance': 'Performance',
    'seller.listings.visibility': 'Visibility',
    'seller.listings.updated': 'Updated',
    'seller.listings.product': 'Product',
    'seller.listings.duplicate': 'Duplicate',
    'seller.listings.confirmDelete': 'Are you sure?',
    'seller.listings.deleteWarning': 'This will permanently delete',
    'seller.listings.editProduct': 'Edit Product',

    // Add Product Panel
    'addProduct.basicInfo': 'Basic Information',
    'addProduct.productName': 'Product Name',
    'addProduct.productNamePlaceholder': 'Enter product name',
    'addProduct.sku': 'SKU',
    'addProduct.skuPlaceholder': 'e.g., SKU-001',
    'addProduct.partNumber': 'Part Number',
    'addProduct.partNumberPlaceholder': 'e.g., PN-12345',
    'addProduct.description': 'Description',
    'addProduct.descriptionPlaceholder': 'Describe your product...',
    'addProduct.pricingInventory': 'Pricing & Inventory',
    'addProduct.price': 'Price',
    'addProduct.stockQuantity': 'Stock Quantity',
    'addProduct.minOrderQty': 'Minimum Order Quantity',
    'addProduct.productDetails': 'Product Details',
    'addProduct.category': 'Category',
    'addProduct.selectCategory': 'Select category',
    'addProduct.manufacturer': 'Manufacturer',
    'addProduct.manufacturerPlaceholder': 'e.g., Siemens',
    'addProduct.brand': 'Brand',
    'addProduct.brandPlaceholder': 'e.g., Industrial Pro',
    'addProduct.specifications': 'Specifications',
    'addProduct.weight': 'Weight',
    'addProduct.dimensions': 'Dimensions (L x W x H)',
    'addProduct.dimensionsPlaceholder': 'e.g., 100 x 50 x 25 cm',
    'addProduct.material': 'Material',
    'addProduct.materialPlaceholder': 'e.g., Stainless Steel',
    'addProduct.productImage': 'Product Image',
    'addProduct.dropImage': 'Drop your image here, or',
    'addProduct.browse': 'browse',
    'addProduct.dragDropUpload': 'Click or drag and drop to upload',
    'addProduct.uploaded': 'Uploaded',
    'addProduct.imageRequirements': 'Image Requirements',
    'addProduct.format': 'Format',
    'addProduct.maxSize': 'Max Size',
    'addProduct.recommended': 'Recommended',
    'addProduct.aspectRatio': 'Aspect Ratio',
    'addProduct.square': '1:1 (Square)',
    'addProduct.wide': '1.91:1 (Wide)',
    'addProduct.imageGuidelines': 'Use a clean, white or neutral background for best results. Product should fill 80% of the frame.',
    'addProduct.saveDraft': 'Save as Draft',
    'addProduct.publish': 'Publish Product',
    // Image Section
    'addProduct.mainProductImage': 'Main Product Image',
    'addProduct.catalog': 'Catalog',
    'addProduct.marketplaceBanner': 'Marketplace Banner',
    'addProduct.featured': 'Featured',
    'addProduct.bannerRequirements': 'Banner Requirements',
    'addProduct.marketplaceBannerDesc': 'This image appears in the marketplace grid and search results. Use a wide banner format for best visibility.',
    'addProduct.productImageDesc': 'Use a clean, white or neutral background. Product should fill 80% of the frame.',
    'addProduct.marketplaceImageDesc': 'Landscape format for marketplace grid. Include product name/branding for visibility.',
    // Visibility Section
    'addProduct.visibilitySection': 'Visibility',
    'addProduct.publishNow': 'Publish Now',
    'addProduct.immediatelyVisible': 'Immediately visible',
    'addProduct.hiddenFromBuyers': 'Hidden from buyers',
    'addProduct.schedule': 'Schedule',
    'addProduct.publishLater': 'Publish later',
    // Auto & Completeness
    'addProduct.auto': 'Auto',
    'addProduct.autoGenerateSku': 'Auto-generate SKU',
    'addProduct.complete': 'Complete',
    'addProduct.readyToPublish': 'Ready to publish',
    'addProduct.missing': 'Missing',
    'addProduct.preview': 'Preview',
    'addProduct.livePreview': 'Live Preview',
    // Variants
    'addProduct.productVariants': 'Product Variants',
    'addProduct.hasVariantsDesc': 'This product has variants (size, color, type)',
    'addProduct.variantSize': 'Size',
    'addProduct.variantColor': 'Color',
    'addProduct.variantType': 'Type',
    'addProduct.variantValue': 'Value',
    'addProduct.variantPriceModifier': '+/- Price',
    'addProduct.variantStock': 'Stock',
    'addProduct.addVariant': 'Add Variant',
    'addProduct.suggested': 'Suggested',
    'addProduct.clickToApply': 'Click to apply',
    // Currency
    'addProduct.currencySAR': 'SAR',
    'addProduct.currencyUSD': 'USD',
    'addProduct.currencyEUR': 'EUR',
    'addProduct.currencyAED': 'AED',
    // Weight units
    'addProduct.weightKg': 'kg',
    'addProduct.weightLb': 'lb',
    'addProduct.weightG': 'g',
    // Categories
    'category.machinery': 'Machinery',
    'category.spareParts': 'Spare Parts',
    'category.electronics': 'Electronics',
    'category.hydraulics': 'Hydraulics',
    'category.pneumatics': 'Pneumatics',
    'category.bearings': 'Bearings',
    'category.motors': 'Motors',
    'category.pumps': 'Pumps',
    'category.valves': 'Valves',
    'category.safetyEquipment': 'Safety Equipment',

    // Item Details Page
    'itemDetails.backToMarketplace': 'Back to Marketplace',
    'itemDetails.sku': 'SKU',
    'itemDetails.partNumber': 'Part Number',
    'itemDetails.compatibleWith': 'Compatible with',
    'itemDetails.inStock': 'In Stock',
    'itemDetails.rfqOnly': 'RFQ Only',
    'itemDetails.outOfStock': 'Out of Stock',
    'itemDetails.requestQuotation': 'Request Quotation',
    'itemDetails.addToRfqList': 'Add to RFQ List',
    'itemDetails.downloadDatasheet': 'Download Datasheet',
    'itemDetails.overview': 'Overview',
    'itemDetails.technicalSpecs': 'Technical Specs',
    'itemDetails.compatibility': 'Compatibility',
    'itemDetails.packagingLogistics': 'Packaging & Logistics',
    'itemDetails.documents': 'Documents',
    'itemDetails.description': 'Description',
    'itemDetails.useCases': 'Use Cases',
    'itemDetails.keyBenefits': 'Key Benefits',
    'itemDetails.rfqIntelligence': 'RFQ Intelligence',
    'itemDetails.totalRfqs': 'Total RFQs',
    'itemDetails.avgResponseTime': 'Avg Response Time',
    'itemDetails.quotesThisMonth': 'Quotes This Month',
    'itemDetails.lastActivity': 'Last Activity',
    'itemDetails.unitPrice': 'Unit Price',
    'itemDetails.moq': 'Min. Order Qty',
    'itemDetails.units': 'units',
    'itemDetails.availableStock': 'Available Stock',
    'itemDetails.leadTime': 'Lead Time',
    'itemDetails.responseTime': 'Response Time',
    'itemDetails.responseSLA': 'Response SLA',
    'itemDetails.yearsActive': 'Years Active',
    'itemDetails.years': 'years',
    'itemDetails.catalogSize': 'Catalog Size',
    'itemDetails.products': 'products',
    'itemDetails.contactViaPlaftorm': 'Contact supplier only via platform',
    'itemDetails.compatibleMachines': 'Compatible Machines',
    'itemDetails.modelYears': 'Model Years',
    'itemDetails.productionLines': 'Production Lines',
    'itemDetails.packagingType': 'Packaging Type',
    'itemDetails.hsCode': 'HS Code',
    'itemDetails.shippingWeight': 'Shipping Weight',
    'itemDetails.packageDimensions': 'Package Dimensions',
    'itemDetails.countryOfOrigin': 'Country of Origin',
    'itemDetails.unitsPerCarton': 'Units per Carton',
    // Item Details - Specifications
    'itemDetails.spec.boreDiameter': 'Bore Diameter',
    'itemDetails.spec.stroke': 'Stroke',
    'itemDetails.spec.operatingPressure': 'Operating Pressure',
    'itemDetails.spec.maxPressure': 'Max Pressure',
    'itemDetails.spec.operatingTemp': 'Operating Temperature',
    'itemDetails.spec.weight': 'Weight',
    'itemDetails.spec.material': 'Material',
    'itemDetails.spec.connectionSize': 'Connection Size',
    'itemDetails.spec.mountingType': 'Mounting Type',
    'itemDetails.spec.cushioning': 'Cushioning',

    // Seller RFQs
    'seller.rfqs.title': 'RFQ Inbox',
    'seller.rfqs.subtitle': 'Respond to quote requests from buyers',
    'seller.rfqs.allRfqs': 'All RFQs',
    'seller.rfqs.noRfqs': 'No RFQs yet',
    'seller.rfqs.noRfqsDesc': 'Incoming quote requests from buyers will appear here',
    'seller.rfqs.rfqNumber': 'RFQ #',
    'seller.rfqs.buyer': 'Buyer',
    'seller.rfqs.partNumber': 'Part Number',
    'seller.rfqs.qty': 'Qty',
    'seller.rfqs.status': 'Status',
    'seller.rfqs.deadline': 'Deadline',
    'seller.rfqs.received': 'Received',
    'seller.rfqs.new': 'New',
    'seller.rfqs.quoted': 'Quoted',
    'seller.rfqs.won': 'Won',
    'seller.rfqs.lost': 'Lost',
    'seller.rfqs.viewed': 'Viewed',
    'seller.rfqs.negotiation': 'Negotiation',
    'seller.rfqs.expired': 'Expired',
    'seller.rfqs.newBadge': 'NEW',
    'seller.rfqs.messages': 'messages',
    'seller.rfqs.requestedPrice': 'Requested Price',
    'seller.rfqs.yourQuote': 'Your Quote',
    'seller.rfqs.sendQuote': 'Send Quote',
    'seller.rfqs.rfqDetails': 'RFQ Details',
    'seller.rfqs.requestedItem': 'Requested Item',
    'seller.rfqs.quantity': 'Quantity',
    'seller.rfqs.buyerInfo': 'Buyer Information',
    'seller.rfqs.pricing': 'Pricing',
    'seller.rfqs.buyerTarget': 'Buyer Target',
    'seller.rfqs.totalValue': 'Total Value',
    'seller.rfqs.submitQuote': 'Submit Quote',
    'seller.rfqs.counterOffer': 'Counter Offer',
    'seller.rfqs.unitPrice': 'Unit Price',
    'seller.rfqs.leadTime': 'Lead Time',
    'seller.rfqs.message': 'Message',
    'seller.rfqs.messagePlaceholder': 'Add any notes or terms for this quote...',
    'seller.rfqs.quoteAccepted': 'Quote Accepted!',
    'seller.rfqs.proceedToOrder': 'This quote has been accepted. Proceed to create the order.',
    'seller.rfqs.quoteLost': 'Quote Not Accepted',
    'seller.rfqs.lostDescription': 'The buyer chose a different supplier for this request.',
    'seller.rfqs.searchPlaceholder': 'Search by RFQ #, item, or buyer...',
    'seller.rfqs.noResults': 'No RFQs match your filters',
    'seller.rfqs.tryAdjusting': 'Try adjusting your search or filter criteria',

    // Seller Orders
    'seller.orders.title': 'Orders',
    'seller.orders.subtitle': 'Manage and fulfill customer orders',
    'seller.orders.noOrders': 'No orders yet',
    'seller.orders.noOrdersDesc': 'Orders from accepted quotes will appear here',
    'seller.orders.orderNumber': 'Order #',
    'seller.orders.buyer': 'Buyer',
    'seller.orders.items': 'Items',
    'seller.orders.item': 'Item',
    'seller.orders.total': 'Total',
    'seller.orders.status': 'Status',
    'seller.orders.date': 'Date',
    'seller.orders.created': 'Created',
    'seller.orders.pending': 'Pending',
    'seller.orders.pendingConfirmation': 'Pending',
    'seller.orders.confirmed': 'Confirmed',
    'seller.orders.inProgress': 'In Progress',
    'seller.orders.shipped': 'Shipped',
    'seller.orders.delivered': 'Delivered',
    'seller.orders.cancelled': 'Cancelled',
    'seller.orders.failed': 'Failed',
    'seller.orders.refunded': 'Refunded',
    // Order Payment Status
    'seller.orders.unpaid': 'Unpaid',
    'seller.orders.authorized': 'Authorized',
    'seller.orders.paid': 'Paid',
    'seller.orders.paymentRefunded': 'Refunded',
    'seller.orders.paymentStatus': 'Payment',
    // Order Fulfillment Status
    'seller.orders.notStarted': 'Not Started',
    'seller.orders.packing': 'Packing',
    'seller.orders.outForDelivery': 'Out for Delivery',
    'seller.orders.fulfillmentDelivered': 'Delivered',
    'seller.orders.fulfillment': 'Fulfillment',
    // Order Actions
    'seller.orders.confirmOrder': 'Confirm Order',
    'seller.orders.shipOrder': 'Ship Order',
    'seller.orders.markDelivered': 'Mark Delivered',
    'seller.orders.cancelOrder': 'Cancel Order',
    'seller.orders.viewDetails': 'View Details',
    'seller.orders.updateStatus': 'Update Status',
    'seller.orders.addTracking': 'Add Tracking',
    // Order Filters
    'seller.orders.filters': 'Filters',
    'seller.orders.allOrders': 'All Orders',
    'seller.orders.allStatus': 'All Status',
    'seller.orders.allPayment': 'All Payment',
    'seller.orders.searchPlaceholder': 'Search by order #, buyer, or item...',
    'seller.orders.clearAll': 'Clear all',
    'seller.orders.noResults': 'No orders match your filters',
    'seller.orders.tryAdjusting': 'Try adjusting your search or filter criteria',
    // Order Sort
    'seller.orders.sortBy': 'Sort by',
    'seller.orders.newest': 'Newest First',
    'seller.orders.oldest': 'Oldest First',
    'seller.orders.totalHighLow': 'Total: High to Low',
    'seller.orders.totalLowHigh': 'Total: Low to High',
    // Order Stats
    'seller.orders.totalOrders': 'Total Orders',
    'seller.orders.pendingOrders': 'Pending',
    'seller.orders.activeOrders': 'Active',
    'seller.orders.completedOrders': 'Completed',
    'seller.orders.revenue': 'Revenue',
    // Order Details
    'seller.orders.orderDetails': 'Order Details',
    'seller.orders.orderInfo': 'Order Information',
    'seller.orders.buyerInfo': 'Buyer Information',
    'seller.orders.itemDetails': 'Item Details',
    'seller.orders.shippingInfo': 'Shipping Information',
    'seller.orders.trackingNumber': 'Tracking Number',
    'seller.orders.carrier': 'Carrier',
    'seller.orders.estimatedDelivery': 'Est. Delivery',
    'seller.orders.notes': 'Notes',
    'seller.orders.sellerNotes': 'Seller Notes',
    'seller.orders.buyerNotes': 'Buyer Notes',
    'seller.orders.internalNotes': 'Internal Notes',
    'seller.orders.auditLog': 'Order History',
    'seller.orders.source': 'Source',
    'seller.orders.fromRfq': 'From RFQ',
    'seller.orders.directBuy': 'Direct Buy',
    'seller.orders.quantity': 'Quantity',
    'seller.orders.unitPrice': 'Unit Price',
    'seller.orders.totalPrice': 'Total Price',
    // Order Confirmation
    'seller.orders.confirmTitle': 'Confirm Order',
    'seller.orders.confirmMessage': 'Are you sure you want to confirm this order?',
    'seller.orders.confirmWarning': 'This will reserve inventory and notify the buyer.',
    // Ship Order
    'seller.orders.shipTitle': 'Ship Order',
    'seller.orders.shipMessage': 'Enter shipping details to mark this order as shipped.',
    'seller.orders.trackingPlaceholder': 'Enter tracking number',
    'seller.orders.carrierPlaceholder': 'Select carrier',
    // Cancel Order
    'seller.orders.cancelTitle': 'Cancel Order',
    'seller.orders.cancelMessage': 'Are you sure you want to cancel this order?',
    'seller.orders.cancelWarning': 'This action cannot be undone. Inventory will be released.',
    'seller.orders.cancelReason': 'Reason (optional)',
    // Table
    'seller.orders.showing': 'Showing',
    'seller.orders.of': 'of',
    'seller.orders.orders': 'orders',
    'seller.orders.selected': 'selected',

    // Seller Analytics
    'seller.analytics.title': 'Analytics',
    'seller.analytics.subtitle': 'Track your performance metrics',
    'seller.analytics.revenue': 'Revenue',
    'seller.analytics.orders': 'Orders',
    'seller.analytics.newBuyers': 'New Buyers',
    'seller.analytics.winRate': 'Win Rate',
    'seller.analytics.vsLastPeriod': 'vs last period',
    'seller.analytics.revenueTrend': 'Revenue Trend',
    'seller.analytics.ordersByCategory': 'Orders by Category',
    'seller.analytics.rfqConversion': 'RFQ Conversion',
    'seller.analytics.topProducts': 'Top Products',
    'seller.analytics.geoDistribution': 'Geographic Distribution',
    'seller.analytics.7days': '7 Days',
    'seller.analytics.30days': '30 Days',
    'seller.analytics.90days': '90 Days',
    'seller.analytics.12months': '12 Months',

    // Seller Workspace
    'seller.workspace.title': 'Workspace',
    'seller.workspace.subtitle': 'Manage your business operations',
    'seller.workspace.dashboard': 'Dashboard',
    'seller.workspace.sales': 'Sales',
    'seller.workspace.customers': 'Customers',
    'seller.workspace.inventory': 'Inventory',
    'seller.workspace.expenses': 'Expenses',
    'seller.workspace.totalRevenue': 'Total Revenue',
    'seller.workspace.totalCustomers': 'Total Customers',
    'seller.workspace.inventoryItems': 'Inventory Items',
    'seller.workspace.monthlyExpenses': 'Monthly Expenses',
    'seller.workspace.salesOverview': 'Sales Overview',
    'seller.workspace.expenseBreakdown': 'Expense Breakdown',
    // Dashboard KPIs
    'seller.dashboard.totalRevenue': 'Total Revenue',
    'seller.dashboard.totalOrders': 'Total Orders',
    'seller.dashboard.activeListings': 'Active Listings',
    'seller.dashboard.pendingRfqs': 'Pending RFQs',
    'seller.dashboard.fromLastMonth': 'from last month',
    'seller.dashboard.noData': 'No data yet',
    'seller.dashboard.noDataDesc': 'Start adding products and receiving orders to see your dashboard analytics',
    'seller.dashboard.error': 'Failed to load dashboard',
    'seller.dashboard.errorDesc': 'Please try again later',
    'seller.dashboard.retry': 'Retry',
    // Sales Page
    'seller.sales.title': 'Sales Management',
    'seller.sales.subtitle': 'Manage and track your sales orders',
    'seller.sales.orderId': 'Order ID',
    'seller.sales.buyer': 'Buyer',
    'seller.sales.product': 'Product',
    'seller.sales.quantity': 'Qty',
    'seller.sales.totalPrice': 'Total',
    'seller.sales.status': 'Status',
    'seller.sales.createdDate': 'Date',
    'seller.sales.actions': 'Actions',
    'seller.sales.allStatus': 'All Status',
    'seller.sales.dateRange': 'Date Range',
    'seller.sales.from': 'From',
    'seller.sales.to': 'To',
    'seller.sales.clearFilters': 'Clear Filters',
    'seller.sales.noOrders': 'No orders yet',
    'seller.sales.noOrdersDesc': 'Your sales orders will appear here',
    'seller.sales.noResults': 'No orders match your filters',
    'seller.sales.updateStatus': 'Update Status',
    'seller.sales.view': 'View',
    'seller.sales.statusUpdated': 'Status updated',
    'seller.sales.statusUpdateFailed': 'Failed to update status',
    'seller.sales.showing': 'Showing',
    'seller.sales.of': 'of',
    'seller.sales.orders': 'orders',
    'seller.sales.page': 'Page',
    'seller.sales.prev': 'Previous',
    'seller.sales.next': 'Next',
    // Customers Page
    'seller.customers.title': 'Customers',
    'seller.customers.subtitle': 'View your customer relationships',
    'seller.customers.name': 'Customer',
    'seller.customers.email': 'Email',
    'seller.customers.company': 'Company',
    'seller.customers.totalOrders': 'Orders',
    'seller.customers.totalSpend': 'Total Spend',
    'seller.customers.lastOrder': 'Last Order',
    'seller.customers.firstOrder': 'First Order',
    'seller.customers.search': 'Search customers...',
    'seller.customers.noCustomers': 'No customers yet',
    'seller.customers.noCustomersDesc': 'Customers will appear here once you receive orders',
    'seller.customers.noResults': 'No customers match your search',
    'seller.customers.details': 'Customer Details',
    'seller.customers.orderHistory': 'Order History',
    'seller.customers.close': 'Close',
    'seller.customers.viewOrder': 'View Order',
    'seller.customers.customerSince': 'Customer since',
    // Inventory Page
    'seller.inventory.title': 'Inventory',
    'seller.inventory.subtitle': 'Manage your stock levels',
    'seller.inventory.sku': 'SKU',
    'seller.inventory.product': 'Product',
    'seller.inventory.category': 'Category',
    'seller.inventory.stockQty': 'Stock',
    'seller.inventory.reservedQty': 'Reserved',
    'seller.inventory.availableQty': 'Available',
    'seller.inventory.status': 'Status',
    'seller.inventory.actions': 'Actions',
    'seller.inventory.search': 'Search inventory...',
    'seller.inventory.allStatus': 'All Status',
    'seller.inventory.inStock': 'In Stock',
    'seller.inventory.lowStock': 'Low Stock',
    'seller.inventory.outOfStock': 'Out of Stock',
    'seller.inventory.noItems': 'No inventory items',
    'seller.inventory.noItemsDesc': 'Add products to start managing your inventory',
    'seller.inventory.noResults': 'No items match your filters',
    'seller.inventory.adjustStock': 'Adjust',
    'seller.inventory.save': 'Save',
    'seller.inventory.cancel': 'Cancel',
    'seller.inventory.stockUpdated': 'Stock updated',
    'seller.inventory.stockUpdateFailed': 'Failed to update stock',
    'seller.inventory.totalItems': 'Total Items',
    'seller.inventory.totalValue': 'Total Value',
    'seller.inventory.lowStockAlert': 'Low Stock Alert',
    // Expenses Page
    'seller.expenses.title': 'Expenses',
    'seller.expenses.subtitle': 'Track your business expenses',
    'seller.expenses.type': 'Type',
    'seller.expenses.amount': 'Amount',
    'seller.expenses.date': 'Date',
    'seller.expenses.notes': 'Notes',
    'seller.expenses.actions': 'Actions',
    'seller.expenses.addExpense': 'Add Expense',
    'seller.expenses.shipping': 'Shipping',
    'seller.expenses.ads': 'Advertising',
    'seller.expenses.platformFee': 'Platform Fee',
    'seller.expenses.supplies': 'Supplies',
    'seller.expenses.other': 'Other',
    'seller.expenses.allTypes': 'All Types',
    'seller.expenses.thisMonth': 'This Month',
    'seller.expenses.lastMonth': 'Last Month',
    'seller.expenses.noExpenses': 'No expenses recorded',
    'seller.expenses.noExpensesDesc': 'Start tracking your business expenses',
    'seller.expenses.noResults': 'No expenses match your filters',
    'seller.expenses.delete': 'Delete',
    'seller.expenses.confirmDelete': 'Delete this expense?',
    'seller.expenses.expenseAdded': 'Expense added',
    'seller.expenses.expenseDeleted': 'Expense deleted',
    'seller.expenses.addExpenseFailed': 'Failed to add expense',
    'seller.expenses.selectType': 'Select type',
    'seller.expenses.enterAmount': 'Enter amount',
    'seller.expenses.optionalNotes': 'Optional notes...',
    'seller.expenses.cancel': 'Cancel',
    'seller.expenses.save': 'Save',

    // Buyer Nav
    'buyer.nav.home': 'Home',
    'buyer.nav.marketplace': 'Marketplace',
    'buyer.nav.requestQuote': 'Request Quote',
    'buyer.nav.myRfqs': 'My RFQs',
    'buyer.nav.orders': 'Orders',
    'buyer.nav.workspace': 'Workspace',
    'buyer.nav.tests': 'Tests',

    // Buyer Tests
    'buyer.tests.title': 'Tests',
    'buyer.tests.subtitle': 'View and track your quality tests',
    'buyer.tests.testName': 'Test Name',
    'buyer.tests.status': 'Status',
    'buyer.tests.score': 'Score',
    'buyer.tests.duration': 'Duration',
    'buyer.tests.date': 'Date',
    'buyer.tests.passed': 'Passed',
    'buyer.tests.pending': 'Pending',
    'buyer.tests.failed': 'Failed',

    // Buyer Home
    'buyer.home.title': 'Industrial Marketplace',
    'buyer.home.subtitle': 'Source parts and equipment from verified suppliers worldwide',
    'buyer.home.searchPlaceholder': 'Search by part number, manufacturer, or keyword...',
    'buyer.home.requestQuote': 'Request Quote',
    'buyer.home.browseCatalog': 'Browse Catalog',
    'buyer.home.viewOrders': 'View Orders',

    // Buyer Marketplace
    'buyer.marketplace.title': 'Marketplace',
    'buyer.marketplace.subtitle': 'Browse parts and equipment from verified suppliers',
    'buyer.marketplace.searchPlaceholder': 'Search by part number, manufacturer...',
    'buyer.marketplace.machinery': 'Machinery',
    'buyer.marketplace.spareParts': 'Spare Parts',
    'buyer.marketplace.electronics': 'Electronics',
    'buyer.marketplace.hydraulics': 'Hydraulics',
    'buyer.marketplace.safetyEquipment': 'Safety Equipment',

    // Buyer Request Quote
    'buyer.rfq.title': 'Request Quote',
    'buyer.rfq.subtitle': 'Get competitive quotes from verified suppliers',
    'buyer.rfq.selectType': 'Select Type',
    'buyer.rfq.partDetails': 'Part Details',
    'buyer.rfq.reviewSubmit': 'Review & Submit',
    'buyer.rfq.whatType': 'What type of RFQ do you need?',
    'buyer.rfq.singlePart': 'Single Part',
    'buyer.rfq.singlePartDesc': 'Request quote for one specific part',
    'buyer.rfq.multipleParts': 'Multiple Parts',
    'buyer.rfq.multiplePartsDesc': 'Request quotes for multiple items',
    'buyer.rfq.enterDetails': 'Enter Part Details',
    'buyer.rfq.partNumber': 'Part Number',
    'buyer.rfq.manufacturer': 'Manufacturer',
    'buyer.rfq.quantity': 'Quantity',
    'buyer.rfq.description': 'Description (Optional)',
    'buyer.rfq.reviewRfq': 'Review Your RFQ',
    'buyer.rfq.willBeSent': 'Your request will be sent to matching suppliers',
    'buyer.rfq.type': 'Type',
    'buyer.rfq.submitRfq': 'Submit RFQ',

    // Buyer My RFQs
    'buyer.myRfqs.title': 'My RFQs',
    'buyer.myRfqs.subtitle': 'Track and manage your quote requests',
    'buyer.myRfqs.newRfq': 'New RFQ',
    'buyer.myRfqs.noRfqs': 'No RFQs yet',
    'buyer.myRfqs.noRfqsDesc': 'Create your first request for quote to get competitive prices from suppliers',
    'buyer.myRfqs.createRfq': 'Create RFQ',
    'buyer.myRfqs.partNumber': 'Part Number',
    'buyer.myRfqs.manufacturer': 'Manufacturer',
    'buyer.myRfqs.qty': 'Qty',
    'buyer.myRfqs.status': 'Status',
    'buyer.myRfqs.quotes': 'Quotes',
    'buyer.myRfqs.created': 'Created',
    'buyer.myRfqs.viewDetails': 'View Details',
    'buyer.myRfqs.pending': 'Pending',
    'buyer.myRfqs.quoted': 'Quoted',
    'buyer.myRfqs.accepted': 'Accepted',
    'buyer.myRfqs.expired': 'Expired',

    // Buyer Orders
    'buyer.orders.title': 'My Orders',
    'buyer.orders.subtitle': 'View and track your purchase orders',
    'buyer.orders.noOrders': 'No orders yet',
    'buyer.orders.noOrdersDesc': 'Your orders will appear here once you accept a quote',
    'buyer.orders.browseMarketplace': 'Browse Marketplace',
    'buyer.orders.orderNumber': 'Order #',
    'buyer.orders.supplier': 'Supplier',
    'buyer.orders.items': 'Items',
    'buyer.orders.total': 'Total',
    'buyer.orders.status': 'Status',
    'buyer.orders.date': 'Date',
    'buyer.orders.processing': 'Processing',
    'buyer.orders.shipped': 'Shipped',
    'buyer.orders.delivered': 'Delivered',
    'buyer.orders.cancelled': 'Cancelled',

    // Buyer Tracking
    'buyer.tracking.title': 'Order Tracking',
    'buyer.tracking.subtitle': 'Track your shipments in real-time',
    'buyer.tracking.enterTracking': 'Enter Tracking Number',
    'buyer.tracking.trackingPlaceholder': 'e.g., NABD-2024-001234',
    'buyer.tracking.orderStatus': 'Order Status',
    'buyer.tracking.tracking': 'Tracking',
    'buyer.tracking.inTransit': 'In Transit',
    'buyer.tracking.orderConfirmed': 'Order Confirmed',
    'buyer.tracking.orderConfirmedDesc': 'Your order has been confirmed',
    'buyer.tracking.shipped': 'Shipped',
    'buyer.tracking.shippedDesc': 'Package picked up by carrier',
    'buyer.tracking.inTransitDesc': 'Package is on its way',
    'buyer.tracking.outForDelivery': 'Out for Delivery',
    'buyer.tracking.outForDeliveryDesc': 'Package will be delivered today',
    'buyer.tracking.delivered': 'Delivered',
    'buyer.tracking.deliveredDesc': 'Package delivered',
    'buyer.tracking.estimated': 'Estimated',

    // Buyer Workspace
    'buyer.workspace.title': 'Workspace',
    'buyer.workspace.subtitle': 'Manage your purchasing operations',
    'buyer.workspace.dashboard': 'Dashboard',
    'buyer.workspace.purchases': 'Purchases',
    'buyer.workspace.suppliers': 'Suppliers',
    'buyer.workspace.inventory': 'Inventory',
    'buyer.workspace.expenses': 'Expenses',
    'buyer.workspace.totalSpend': 'Total Spend',
    'buyer.workspace.activeOrders': 'Active Orders',
    'buyer.workspace.pendingRfqs': 'Pending RFQs',
    'buyer.workspace.suppliersCount': 'Suppliers',
    'buyer.workspace.spendingOverview': 'Spending Overview',
  },
  ar: {
    // Common
    'common.signOut': 'تسجيل الخروج',
    'common.seller': 'بائع',
    'common.buyer': 'مشتري',
    'common.search': 'بحث',
    'common.viewAll': 'عرض الكل',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.actions': 'إجراءات',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'common.back': 'رجوع',
    'common.continue': 'متابعة',
    'common.filters': 'تصفية',
    'common.all': 'الكل',
    'common.new': 'جديد',
    'common.view': 'عرض',
    'common.track': 'تتبع',
    'common.details': 'التفاصيل',
    'common.confirm': 'تأكيد',
    'common.ship': 'شحن',
    'common.quote': 'تسعير',
    'common.suppliers': 'الموردين',
    'common.products': 'المنتجات',
    'common.onTimeDelivery': 'التوصيل في الوقت',
    'common.units': 'وحدات',
    'common.unit': 'وحدة',
    'common.days': 'أيام',

    // Seller Nav
    'seller.nav.home': 'الرئيسية',
    'seller.nav.listings': 'المنتجات',
    'seller.nav.rfqs': 'طلبات الأسعار',
    'seller.nav.orders': 'الطلبات',
    'seller.nav.analytics': 'التحليلات',
    'seller.nav.workspace': 'مساحة العمل',
    'seller.nav.inventory': 'المخزون',
    'seller.nav.logistics': 'اللوجستيات',
    'seller.nav.tracking': 'التتبع المباشر',
    'seller.nav.settings': 'الإعدادات',
    'seller.nav.tests': 'الاختبارات',

    // Seller Tests
    'seller.tests.title': 'الاختبارات',
    'seller.tests.subtitle': 'إدارة وتتبع اختبارات الشهادات',
    'seller.tests.testName': 'اسم الاختبار',
    'seller.tests.status': 'الحالة',
    'seller.tests.score': 'الدرجة',
    'seller.tests.duration': 'المدة',
    'seller.tests.date': 'التاريخ',
    'seller.tests.passed': 'ناجح',
    'seller.tests.pending': 'قيد الانتظار',
    'seller.tests.failed': 'راسب',

    // Seller Home
    'seller.home.title': 'لوحة تحكم البائع',
    'seller.home.subtitle': 'إدارة منتجاتك، والرد على طلبات الأسعار، وتنمية أعمالك',
    'seller.home.revenue': 'الإيرادات (هذا الشهر)',
    'seller.home.activeOrders': 'الطلبات النشطة',
    'seller.home.rfqsThisMonth': 'طلبات الأسعار هذا الشهر',
    'seller.home.fromLastMonth': 'من الشهر الماضي',
    'seller.home.manageListings': 'إدارة المنتجات',
    'seller.home.viewListings': 'عرض المنتجات',
    'seller.home.activeProducts': 'منتج نشط في الكتالوج',
    'seller.home.rfqInbox': 'صندوق طلبات الأسعار',
    'seller.home.viewRfqs': 'عرض الطلبات',
    'seller.home.newRequests': 'طلبات جديدة بانتظار الرد',

    // Seller Listings
    'seller.listings.title': 'المنتجات',
    'seller.listings.subtitle': 'إدارة كتالوج المنتجات',
    'seller.listings.addProduct': 'إضافة منتج',
    'seller.listings.searchPlaceholder': 'البحث برمز المنتج أو الاسم أو الشركة المصنعة...',
    'seller.listings.allCategories': 'جميع الفئات',
    'seller.listings.allStatus': 'جميع الحالات',
    'seller.listings.noListings': 'لا توجد منتجات بعد',
    'seller.listings.noListingsDesc': 'أضف أول منتج لبدء استقبال طلبات الأسعار',
    'seller.listings.sku': 'رمز المنتج',
    'seller.listings.productName': 'اسم المنتج',
    'seller.listings.manufacturer': 'الشركة المصنعة',
    'seller.listings.category': 'الفئة',
    'seller.listings.price': 'السعر',
    'seller.listings.stock': 'المخزون',
    'seller.listings.status': 'الحالة',
    'seller.listings.active': 'نشط',
    'seller.listings.draft': 'مسودة',
    'seller.listings.outOfStock': 'نفذ المخزون',
    // Listings Filter & Table
    'seller.listings.filters': 'تصفية',
    'seller.listings.searchBySku': 'البحث بالاسم أو رمز المنتج...',
    'seller.listings.allStock': 'جميع المخزون',
    'seller.listings.allVisibility': 'جميع الظهور',
    'seller.listings.inStock': 'متوفر',
    'seller.listings.lowStock': 'مخزون منخفض',
    'seller.listings.public': 'عام',
    'seller.listings.hidden': 'مخفي',
    'seller.listings.rfqOnly': 'طلب سعر فقط',
    'seller.listings.sortBy': 'ترتيب حسب',
    'seller.listings.lastUpdated': 'آخر تحديث',
    'seller.listings.nameAZ': 'الاسم أ-ي',
    'seller.listings.priceLowHigh': 'السعر: من الأقل للأعلى',
    'seller.listings.priceHighLow': 'السعر: من الأعلى للأقل',
    'seller.listings.stockLowHigh': 'المخزون: من الأقل للأعلى',
    'seller.listings.stockHighLow': 'المخزون: من الأعلى للأقل',
    'seller.listings.clearAll': 'مسح الكل',
    'seller.listings.selected': 'محدد',
    'seller.listings.setActive': 'تنشيط',
    'seller.listings.setDraft': 'مسودة',
    'seller.listings.makePublic': 'جعله عام',
    'seller.listings.makeHidden': 'إخفاء',
    'seller.listings.total': 'الإجمالي',
    'seller.listings.showing': 'عرض',
    'seller.listings.of': 'من',
    'seller.listings.products': 'منتجات',
    'seller.listings.noProductsMatch': 'لا توجد منتجات تطابق معايير البحث',
    'seller.listings.tryAdjusting': 'حاول تعديل معايير البحث أو التصفية',
    'seller.listings.noProductsYet': 'لا توجد منتجات بعد',
    'seller.listings.startBuilding': 'ابدأ ببناء كتالوج منتجاتك بإضافة أول منتج',
    'seller.listings.addFirstProduct': 'أضف أول منتج',
    'seller.listings.orders': 'طلبات',
    'seller.listings.rfqs': 'طلبات أسعار',
    'seller.listings.performance': 'الأداء',
    'seller.listings.visibility': 'الظهور',
    'seller.listings.updated': 'التحديث',
    'seller.listings.product': 'المنتج',
    'seller.listings.duplicate': 'نسخ',
    'seller.listings.confirmDelete': 'هل أنت متأكد؟',
    'seller.listings.deleteWarning': 'سيتم حذف هذا المنتج نهائياً',
    'seller.listings.editProduct': 'تعديل المنتج',

    // Add Product Panel
    'addProduct.basicInfo': 'المعلومات الأساسية',
    'addProduct.productName': 'اسم المنتج',
    'addProduct.productNamePlaceholder': 'أدخل اسم المنتج',
    'addProduct.sku': 'رمز المنتج',
    'addProduct.skuPlaceholder': 'مثال: SKU-001',
    'addProduct.partNumber': 'رقم القطعة',
    'addProduct.partNumberPlaceholder': 'مثال: PN-12345',
    'addProduct.description': 'الوصف',
    'addProduct.descriptionPlaceholder': 'صف منتجك...',
    'addProduct.pricingInventory': 'التسعير والمخزون',
    'addProduct.price': 'السعر',
    'addProduct.stockQuantity': 'كمية المخزون',
    'addProduct.minOrderQty': 'الحد الأدنى للطلب',
    'addProduct.productDetails': 'تفاصيل المنتج',
    'addProduct.category': 'الفئة',
    'addProduct.selectCategory': 'اختر الفئة',
    'addProduct.manufacturer': 'الشركة المصنعة',
    'addProduct.manufacturerPlaceholder': 'مثال: سيمنز',
    'addProduct.brand': 'العلامة التجارية',
    'addProduct.brandPlaceholder': 'مثال: Industrial Pro',
    'addProduct.specifications': 'المواصفات',
    'addProduct.weight': 'الوزن',
    'addProduct.dimensions': 'الأبعاد (الطول × العرض × الارتفاع)',
    'addProduct.dimensionsPlaceholder': 'مثال: 100 × 50 × 25 سم',
    'addProduct.material': 'المادة',
    'addProduct.materialPlaceholder': 'مثال: فولاذ مقاوم للصدأ',
    'addProduct.productImage': 'صورة المنتج',
    'addProduct.dropImage': 'أفلت صورتك هنا، أو',
    'addProduct.browse': 'تصفح',
    'addProduct.dragDropUpload': 'انقر أو اسحب وأفلت للرفع',
    'addProduct.uploaded': 'تم الرفع',
    'addProduct.imageRequirements': 'متطلبات الصورة',
    'addProduct.format': 'الصيغة',
    'addProduct.maxSize': 'الحجم الأقصى',
    'addProduct.recommended': 'الموصى به',
    'addProduct.aspectRatio': 'نسبة العرض للارتفاع',
    'addProduct.square': '1:1 (مربع)',
    'addProduct.wide': '1.91:1 (عريض)',
    'addProduct.imageGuidelines': 'استخدم خلفية نظيفة، بيضاء أو محايدة للحصول على أفضل النتائج. يجب أن يملأ المنتج 80% من الإطار.',
    'addProduct.saveDraft': 'حفظ كمسودة',
    'addProduct.publish': 'نشر المنتج',
    // Image Section
    'addProduct.mainProductImage': 'صورة المنتج الرئيسية',
    'addProduct.catalog': 'الكتالوج',
    'addProduct.marketplaceBanner': 'بانر السوق',
    'addProduct.featured': 'مميز',
    'addProduct.bannerRequirements': 'متطلبات البانر',
    'addProduct.marketplaceBannerDesc': 'تظهر هذه الصورة في شبكة السوق ونتائج البحث. استخدم تنسيق بانر عريض للحصول على أفضل رؤية.',
    'addProduct.productImageDesc': 'استخدم خلفية نظيفة، بيضاء أو محايدة. يجب أن يملأ المنتج 80% من الإطار.',
    'addProduct.marketplaceImageDesc': 'تنسيق أفقي لشبكة السوق. أضف اسم المنتج أو العلامة التجارية للوضوح.',
    // Visibility Section
    'addProduct.visibilitySection': 'الظهور',
    'addProduct.publishNow': 'نشر الآن',
    'addProduct.immediatelyVisible': 'مرئي فوراً',
    'addProduct.hiddenFromBuyers': 'مخفي من المشترين',
    'addProduct.schedule': 'جدولة',
    'addProduct.publishLater': 'نشر لاحقاً',
    // Auto & Completeness
    'addProduct.auto': 'تلقائي',
    'addProduct.autoGenerateSku': 'توليد رمز تلقائي',
    'addProduct.complete': 'مكتمل',
    'addProduct.readyToPublish': 'جاهز للنشر',
    'addProduct.missing': 'ناقص',
    'addProduct.preview': 'معاينة',
    'addProduct.livePreview': 'معاينة مباشرة',
    // Variants
    'addProduct.productVariants': 'متغيرات المنتج',
    'addProduct.hasVariantsDesc': 'هذا المنتج له متغيرات (حجم، لون، نوع)',
    'addProduct.variantSize': 'الحجم',
    'addProduct.variantColor': 'اللون',
    'addProduct.variantType': 'النوع',
    'addProduct.variantValue': 'القيمة',
    'addProduct.variantPriceModifier': '+/- السعر',
    'addProduct.variantStock': 'المخزون',
    'addProduct.addVariant': 'إضافة متغير',
    'addProduct.suggested': 'مقترح',
    'addProduct.clickToApply': 'انقر للتطبيق',
    // Currency
    'addProduct.currencySAR': 'ر.س',
    'addProduct.currencyUSD': 'دولار',
    'addProduct.currencyEUR': 'يورو',
    'addProduct.currencyAED': 'درهم',
    // Weight units
    'addProduct.weightKg': 'كجم',
    'addProduct.weightLb': 'رطل',
    'addProduct.weightG': 'جم',
    // Categories
    'category.machinery': 'الآلات',
    'category.spareParts': 'قطع الغيار',
    'category.electronics': 'الإلكترونيات',
    'category.hydraulics': 'الهيدروليك',
    'category.pneumatics': 'الهوائيات',
    'category.bearings': 'المحامل',
    'category.motors': 'المحركات',
    'category.pumps': 'المضخات',
    'category.valves': 'الصمامات',
    'category.safetyEquipment': 'معدات السلامة',

    // Item Details Page
    'itemDetails.backToMarketplace': 'العودة للسوق',
    'itemDetails.sku': 'رمز المنتج',
    'itemDetails.partNumber': 'رقم القطعة',
    'itemDetails.compatibleWith': 'متوافق مع',
    'itemDetails.inStock': 'متوفر',
    'itemDetails.rfqOnly': 'طلب سعر فقط',
    'itemDetails.outOfStock': 'نفذ المخزون',
    'itemDetails.requestQuotation': 'طلب عرض سعر',
    'itemDetails.addToRfqList': 'إضافة لقائمة الطلبات',
    'itemDetails.downloadDatasheet': 'تحميل المواصفات',
    'itemDetails.overview': 'نظرة عامة',
    'itemDetails.technicalSpecs': 'المواصفات الفنية',
    'itemDetails.compatibility': 'التوافق',
    'itemDetails.packagingLogistics': 'التغليف والشحن',
    'itemDetails.documents': 'المستندات',
    'itemDetails.description': 'الوصف',
    'itemDetails.useCases': 'حالات الاستخدام',
    'itemDetails.keyBenefits': 'المزايا الرئيسية',
    'itemDetails.rfqIntelligence': 'معلومات طلبات الأسعار',
    'itemDetails.totalRfqs': 'إجمالي الطلبات',
    'itemDetails.avgResponseTime': 'متوسط وقت الرد',
    'itemDetails.quotesThisMonth': 'عروض هذا الشهر',
    'itemDetails.lastActivity': 'آخر نشاط',
    'itemDetails.unitPrice': 'سعر الوحدة',
    'itemDetails.moq': 'الحد الأدنى للطلب',
    'itemDetails.units': 'وحدات',
    'itemDetails.availableStock': 'المخزون المتاح',
    'itemDetails.leadTime': 'وقت التسليم',
    'itemDetails.responseTime': 'وقت الرد',
    'itemDetails.responseSLA': 'التزام وقت الرد',
    'itemDetails.yearsActive': 'سنوات العمل',
    'itemDetails.years': 'سنوات',
    'itemDetails.catalogSize': 'حجم الكتالوج',
    'itemDetails.products': 'منتجات',
    'itemDetails.contactViaPlaftorm': 'التواصل مع المورد عبر المنصة فقط',
    'itemDetails.compatibleMachines': 'الآلات المتوافقة',
    'itemDetails.modelYears': 'سنوات الموديل',
    'itemDetails.productionLines': 'خطوط الإنتاج',
    'itemDetails.packagingType': 'نوع التغليف',
    'itemDetails.hsCode': 'رمز النظام المنسق',
    'itemDetails.shippingWeight': 'وزن الشحن',
    'itemDetails.packageDimensions': 'أبعاد العبوة',
    'itemDetails.countryOfOrigin': 'بلد المنشأ',
    'itemDetails.unitsPerCarton': 'وحدات لكل كرتون',
    // Item Details - Specifications
    'itemDetails.spec.boreDiameter': 'قطر التجويف',
    'itemDetails.spec.stroke': 'الشوط',
    'itemDetails.spec.operatingPressure': 'ضغط التشغيل',
    'itemDetails.spec.maxPressure': 'الضغط الأقصى',
    'itemDetails.spec.operatingTemp': 'درجة حرارة التشغيل',
    'itemDetails.spec.weight': 'الوزن',
    'itemDetails.spec.material': 'المادة',
    'itemDetails.spec.connectionSize': 'حجم التوصيل',
    'itemDetails.spec.mountingType': 'نوع التركيب',
    'itemDetails.spec.cushioning': 'التخميد',

    // Seller RFQs
    'seller.rfqs.title': 'صندوق طلبات الأسعار',
    'seller.rfqs.subtitle': 'الرد على طلبات الأسعار من المشترين',
    'seller.rfqs.allRfqs': 'جميع الطلبات',
    'seller.rfqs.noRfqs': 'لا توجد طلبات بعد',
    'seller.rfqs.noRfqsDesc': 'ستظهر طلبات الأسعار الواردة من المشترين هنا',
    'seller.rfqs.rfqNumber': 'رقم الطلب',
    'seller.rfqs.buyer': 'المشتري',
    'seller.rfqs.partNumber': 'رقم القطعة',
    'seller.rfqs.qty': 'الكمية',
    'seller.rfqs.status': 'الحالة',
    'seller.rfqs.deadline': 'الموعد النهائي',
    'seller.rfqs.received': 'تاريخ الاستلام',
    'seller.rfqs.new': 'جديد',
    'seller.rfqs.quoted': 'تم التسعير',
    'seller.rfqs.won': 'فاز',
    'seller.rfqs.lost': 'خسر',
    'seller.rfqs.viewed': 'تم العرض',
    'seller.rfqs.negotiation': 'مفاوضة',
    'seller.rfqs.expired': 'منتهي الصلاحية',
    'seller.rfqs.newBadge': 'جديد',
    'seller.rfqs.messages': 'رسائل',
    'seller.rfqs.requestedPrice': 'السعر المطلوب',
    'seller.rfqs.yourQuote': 'عرضك',
    'seller.rfqs.sendQuote': 'إرسال العرض',
    'seller.rfqs.rfqDetails': 'تفاصيل الطلب',
    'seller.rfqs.requestedItem': 'المنتج المطلوب',
    'seller.rfqs.quantity': 'الكمية',
    'seller.rfqs.buyerInfo': 'معلومات المشتري',
    'seller.rfqs.pricing': 'التسعير',
    'seller.rfqs.buyerTarget': 'السعر المستهدف',
    'seller.rfqs.totalValue': 'القيمة الإجمالية',
    'seller.rfqs.submitQuote': 'إرسال العرض',
    'seller.rfqs.counterOffer': 'عرض مضاد',
    'seller.rfqs.unitPrice': 'سعر الوحدة',
    'seller.rfqs.leadTime': 'مدة التسليم',
    'seller.rfqs.message': 'رسالة',
    'seller.rfqs.messagePlaceholder': 'أضف أي ملاحظات أو شروط لهذا العرض...',
    'seller.rfqs.quoteAccepted': 'تم قبول العرض!',
    'seller.rfqs.proceedToOrder': 'تم قبول هذا العرض. تابع لإنشاء الطلب.',
    'seller.rfqs.quoteLost': 'لم يتم قبول العرض',
    'seller.rfqs.lostDescription': 'اختار المشتري موردًا آخر لهذا الطلب.',
    'seller.rfqs.searchPlaceholder': 'البحث برقم الطلب أو المنتج أو المشتري...',
    'seller.rfqs.noResults': 'لا توجد طلبات تطابق البحث',
    'seller.rfqs.tryAdjusting': 'حاول تعديل معايير البحث أو الفلترة',

    // Seller Orders
    'seller.orders.title': 'الطلبات',
    'seller.orders.subtitle': 'إدارة وتنفيذ طلبات العملاء',
    'seller.orders.noOrders': 'لا توجد طلبات بعد',
    'seller.orders.noOrdersDesc': 'ستظهر الطلبات من عروض الأسعار المقبولة هنا',
    'seller.orders.orderNumber': 'رقم الطلب',
    'seller.orders.buyer': 'المشتري',
    'seller.orders.items': 'المنتجات',
    'seller.orders.item': 'المنتج',
    'seller.orders.total': 'الإجمالي',
    'seller.orders.status': 'الحالة',
    'seller.orders.date': 'التاريخ',
    'seller.orders.created': 'تاريخ الإنشاء',
    'seller.orders.pending': 'قيد الانتظار',
    'seller.orders.pendingConfirmation': 'بانتظار التأكيد',
    'seller.orders.confirmed': 'مؤكد',
    'seller.orders.inProgress': 'قيد التنفيذ',
    'seller.orders.shipped': 'تم الشحن',
    'seller.orders.delivered': 'تم التوصيل',
    'seller.orders.cancelled': 'ملغي',
    'seller.orders.failed': 'فشل',
    'seller.orders.refunded': 'مسترد',
    // Order Payment Status
    'seller.orders.unpaid': 'غير مدفوع',
    'seller.orders.authorized': 'مصرح',
    'seller.orders.paid': 'مدفوع',
    'seller.orders.paymentRefunded': 'مسترد',
    'seller.orders.paymentStatus': 'الدفع',
    // Order Fulfillment Status
    'seller.orders.notStarted': 'لم يبدأ',
    'seller.orders.packing': 'جاري التعبئة',
    'seller.orders.outForDelivery': 'في الطريق للتوصيل',
    'seller.orders.fulfillmentDelivered': 'تم التوصيل',
    'seller.orders.fulfillment': 'التنفيذ',
    // Order Actions
    'seller.orders.confirmOrder': 'تأكيد الطلب',
    'seller.orders.shipOrder': 'شحن الطلب',
    'seller.orders.markDelivered': 'تحديد كمُستلَم',
    'seller.orders.cancelOrder': 'إلغاء الطلب',
    'seller.orders.viewDetails': 'عرض التفاصيل',
    'seller.orders.updateStatus': 'تحديث الحالة',
    'seller.orders.addTracking': 'إضافة التتبع',
    // Order Filters
    'seller.orders.filters': 'تصفية',
    'seller.orders.allOrders': 'جميع الطلبات',
    'seller.orders.allStatus': 'جميع الحالات',
    'seller.orders.allPayment': 'جميع المدفوعات',
    'seller.orders.searchPlaceholder': 'البحث برقم الطلب أو المشتري أو المنتج...',
    'seller.orders.clearAll': 'مسح الكل',
    'seller.orders.noResults': 'لا توجد طلبات تطابق البحث',
    'seller.orders.tryAdjusting': 'حاول تعديل معايير البحث أو التصفية',
    // Order Sort
    'seller.orders.sortBy': 'ترتيب حسب',
    'seller.orders.newest': 'الأحدث أولاً',
    'seller.orders.oldest': 'الأقدم أولاً',
    'seller.orders.totalHighLow': 'الإجمالي: من الأعلى للأقل',
    'seller.orders.totalLowHigh': 'الإجمالي: من الأقل للأعلى',
    // Order Stats
    'seller.orders.totalOrders': 'إجمالي الطلبات',
    'seller.orders.pendingOrders': 'قيد الانتظار',
    'seller.orders.activeOrders': 'نشط',
    'seller.orders.completedOrders': 'مكتمل',
    'seller.orders.revenue': 'الإيرادات',
    // Order Details
    'seller.orders.orderDetails': 'تفاصيل الطلب',
    'seller.orders.orderInfo': 'معلومات الطلب',
    'seller.orders.buyerInfo': 'معلومات المشتري',
    'seller.orders.itemDetails': 'تفاصيل المنتج',
    'seller.orders.shippingInfo': 'معلومات الشحن',
    'seller.orders.trackingNumber': 'رقم التتبع',
    'seller.orders.carrier': 'شركة الشحن',
    'seller.orders.estimatedDelivery': 'التسليم المتوقع',
    'seller.orders.notes': 'ملاحظات',
    'seller.orders.sellerNotes': 'ملاحظات البائع',
    'seller.orders.buyerNotes': 'ملاحظات المشتري',
    'seller.orders.internalNotes': 'ملاحظات داخلية',
    'seller.orders.auditLog': 'سجل الطلب',
    'seller.orders.source': 'المصدر',
    'seller.orders.fromRfq': 'من طلب سعر',
    'seller.orders.directBuy': 'شراء مباشر',
    'seller.orders.quantity': 'الكمية',
    'seller.orders.unitPrice': 'سعر الوحدة',
    'seller.orders.totalPrice': 'السعر الإجمالي',
    // Order Confirmation
    'seller.orders.confirmTitle': 'تأكيد الطلب',
    'seller.orders.confirmMessage': 'هل أنت متأكد من تأكيد هذا الطلب؟',
    'seller.orders.confirmWarning': 'سيتم حجز المخزون وإخطار المشتري.',
    // Ship Order
    'seller.orders.shipTitle': 'شحن الطلب',
    'seller.orders.shipMessage': 'أدخل تفاصيل الشحن لتحديد الطلب كمشحون.',
    'seller.orders.trackingPlaceholder': 'أدخل رقم التتبع',
    'seller.orders.carrierPlaceholder': 'اختر شركة الشحن',
    // Cancel Order
    'seller.orders.cancelTitle': 'إلغاء الطلب',
    'seller.orders.cancelMessage': 'هل أنت متأكد من إلغاء هذا الطلب؟',
    'seller.orders.cancelWarning': 'لا يمكن التراجع عن هذا الإجراء. سيتم إعادة المخزون.',
    'seller.orders.cancelReason': 'السبب (اختياري)',
    // Table
    'seller.orders.showing': 'عرض',
    'seller.orders.of': 'من',
    'seller.orders.orders': 'طلبات',
    'seller.orders.selected': 'محدد',

    // Seller Analytics
    'seller.analytics.title': 'التحليلات',
    'seller.analytics.subtitle': 'تتبع مؤشرات أدائك',
    'seller.analytics.revenue': 'الإيرادات',
    'seller.analytics.orders': 'الطلبات',
    'seller.analytics.newBuyers': 'مشترين جدد',
    'seller.analytics.winRate': 'معدل الفوز',
    'seller.analytics.vsLastPeriod': 'مقارنة بالفترة السابقة',
    'seller.analytics.revenueTrend': 'اتجاه الإيرادات',
    'seller.analytics.ordersByCategory': 'الطلبات حسب الفئة',
    'seller.analytics.rfqConversion': 'معدل تحويل الطلبات',
    'seller.analytics.topProducts': 'أفضل المنتجات',
    'seller.analytics.geoDistribution': 'التوزيع الجغرافي',
    'seller.analytics.7days': '٧ أيام',
    'seller.analytics.30days': '٣٠ يوم',
    'seller.analytics.90days': '٩٠ يوم',
    'seller.analytics.12months': '١٢ شهر',

    // Seller Workspace
    'seller.workspace.title': 'مساحة العمل',
    'seller.workspace.subtitle': 'إدارة عمليات أعمالك',
    'seller.workspace.dashboard': 'لوحة التحكم',
    'seller.workspace.sales': 'المبيعات',
    'seller.workspace.customers': 'العملاء',
    'seller.workspace.inventory': 'المخزون',
    'seller.workspace.expenses': 'المصروفات',
    'seller.workspace.totalRevenue': 'إجمالي الإيرادات',
    'seller.workspace.totalCustomers': 'إجمالي العملاء',
    'seller.workspace.inventoryItems': 'عناصر المخزون',
    'seller.workspace.monthlyExpenses': 'المصروفات الشهرية',
    'seller.workspace.salesOverview': 'نظرة عامة على المبيعات',
    'seller.workspace.expenseBreakdown': 'تفاصيل المصروفات',
    // Dashboard KPIs
    'seller.dashboard.totalRevenue': 'إجمالي الإيرادات',
    'seller.dashboard.totalOrders': 'إجمالي الطلبات',
    'seller.dashboard.activeListings': 'المنتجات النشطة',
    'seller.dashboard.pendingRfqs': 'طلبات الأسعار المعلقة',
    'seller.dashboard.fromLastMonth': 'من الشهر الماضي',
    'seller.dashboard.noData': 'لا توجد بيانات بعد',
    'seller.dashboard.noDataDesc': 'ابدأ بإضافة منتجات واستلام طلبات لمشاهدة تحليلات لوحة التحكم',
    'seller.dashboard.error': 'فشل في تحميل لوحة التحكم',
    'seller.dashboard.errorDesc': 'يرجى المحاولة مرة أخرى لاحقاً',
    'seller.dashboard.retry': 'إعادة المحاولة',
    // Sales Page
    'seller.sales.title': 'إدارة المبيعات',
    'seller.sales.subtitle': 'إدارة وتتبع طلبات المبيعات',
    'seller.sales.orderId': 'رقم الطلب',
    'seller.sales.buyer': 'المشتري',
    'seller.sales.product': 'المنتج',
    'seller.sales.quantity': 'الكمية',
    'seller.sales.totalPrice': 'الإجمالي',
    'seller.sales.status': 'الحالة',
    'seller.sales.createdDate': 'التاريخ',
    'seller.sales.actions': 'إجراءات',
    'seller.sales.allStatus': 'جميع الحالات',
    'seller.sales.dateRange': 'نطاق التاريخ',
    'seller.sales.from': 'من',
    'seller.sales.to': 'إلى',
    'seller.sales.clearFilters': 'مسح الفلاتر',
    'seller.sales.noOrders': 'لا توجد طلبات بعد',
    'seller.sales.noOrdersDesc': 'ستظهر طلبات المبيعات هنا',
    'seller.sales.noResults': 'لا توجد طلبات تطابق الفلاتر',
    'seller.sales.updateStatus': 'تحديث الحالة',
    'seller.sales.view': 'عرض',
    'seller.sales.statusUpdated': 'تم تحديث الحالة',
    'seller.sales.statusUpdateFailed': 'فشل في تحديث الحالة',
    'seller.sales.showing': 'عرض',
    'seller.sales.of': 'من',
    'seller.sales.orders': 'طلبات',
    'seller.sales.page': 'صفحة',
    'seller.sales.prev': 'السابق',
    'seller.sales.next': 'التالي',
    // Customers Page
    'seller.customers.title': 'العملاء',
    'seller.customers.subtitle': 'عرض علاقات العملاء',
    'seller.customers.name': 'العميل',
    'seller.customers.email': 'البريد الإلكتروني',
    'seller.customers.company': 'الشركة',
    'seller.customers.totalOrders': 'الطلبات',
    'seller.customers.totalSpend': 'إجمالي الإنفاق',
    'seller.customers.lastOrder': 'آخر طلب',
    'seller.customers.firstOrder': 'أول طلب',
    'seller.customers.search': 'البحث عن عملاء...',
    'seller.customers.noCustomers': 'لا يوجد عملاء بعد',
    'seller.customers.noCustomersDesc': 'سيظهر العملاء هنا بمجرد استلام الطلبات',
    'seller.customers.noResults': 'لا يوجد عملاء يطابقون البحث',
    'seller.customers.details': 'تفاصيل العميل',
    'seller.customers.orderHistory': 'سجل الطلبات',
    'seller.customers.close': 'إغلاق',
    'seller.customers.viewOrder': 'عرض الطلب',
    'seller.customers.customerSince': 'عميل منذ',
    // Inventory Page
    'seller.inventory.title': 'المخزون',
    'seller.inventory.subtitle': 'إدارة مستويات المخزون',
    'seller.inventory.sku': 'رمز المنتج',
    'seller.inventory.product': 'المنتج',
    'seller.inventory.category': 'الفئة',
    'seller.inventory.stockQty': 'المخزون',
    'seller.inventory.reservedQty': 'محجوز',
    'seller.inventory.availableQty': 'متاح',
    'seller.inventory.status': 'الحالة',
    'seller.inventory.actions': 'إجراءات',
    'seller.inventory.search': 'البحث في المخزون...',
    'seller.inventory.allStatus': 'جميع الحالات',
    'seller.inventory.inStock': 'متوفر',
    'seller.inventory.lowStock': 'مخزون منخفض',
    'seller.inventory.outOfStock': 'نفد المخزون',
    'seller.inventory.noItems': 'لا توجد عناصر في المخزون',
    'seller.inventory.noItemsDesc': 'أضف منتجات لبدء إدارة المخزون',
    'seller.inventory.noResults': 'لا توجد عناصر تطابق الفلاتر',
    'seller.inventory.adjustStock': 'تعديل',
    'seller.inventory.save': 'حفظ',
    'seller.inventory.cancel': 'إلغاء',
    'seller.inventory.stockUpdated': 'تم تحديث المخزون',
    'seller.inventory.stockUpdateFailed': 'فشل في تحديث المخزون',
    'seller.inventory.totalItems': 'إجمالي العناصر',
    'seller.inventory.totalValue': 'القيمة الإجمالية',
    'seller.inventory.lowStockAlert': 'تنبيه مخزون منخفض',
    // Expenses Page
    'seller.expenses.title': 'المصروفات',
    'seller.expenses.subtitle': 'تتبع مصروفات العمل',
    'seller.expenses.type': 'النوع',
    'seller.expenses.amount': 'المبلغ',
    'seller.expenses.date': 'التاريخ',
    'seller.expenses.notes': 'ملاحظات',
    'seller.expenses.actions': 'إجراءات',
    'seller.expenses.addExpense': 'إضافة مصروف',
    'seller.expenses.shipping': 'الشحن',
    'seller.expenses.ads': 'الإعلانات',
    'seller.expenses.platformFee': 'رسوم المنصة',
    'seller.expenses.supplies': 'المستلزمات',
    'seller.expenses.other': 'أخرى',
    'seller.expenses.allTypes': 'جميع الأنواع',
    'seller.expenses.thisMonth': 'هذا الشهر',
    'seller.expenses.lastMonth': 'الشهر الماضي',
    'seller.expenses.noExpenses': 'لا توجد مصروفات مسجلة',
    'seller.expenses.noExpensesDesc': 'ابدأ بتتبع مصروفات عملك',
    'seller.expenses.noResults': 'لا توجد مصروفات تطابق الفلاتر',
    'seller.expenses.delete': 'حذف',
    'seller.expenses.confirmDelete': 'حذف هذا المصروف؟',
    'seller.expenses.expenseAdded': 'تمت إضافة المصروف',
    'seller.expenses.expenseDeleted': 'تم حذف المصروف',
    'seller.expenses.addExpenseFailed': 'فشل في إضافة المصروف',
    'seller.expenses.selectType': 'اختر النوع',
    'seller.expenses.enterAmount': 'أدخل المبلغ',
    'seller.expenses.optionalNotes': 'ملاحظات اختيارية...',
    'seller.expenses.cancel': 'إلغاء',
    'seller.expenses.save': 'حفظ',

    // Buyer Nav
    'buyer.nav.home': 'الرئيسية',
    'buyer.nav.marketplace': 'السوق',
    'buyer.nav.requestQuote': 'طلب سعر',
    'buyer.nav.myRfqs': 'طلباتي',
    'buyer.nav.orders': 'الطلبات',
    'buyer.nav.workspace': 'مساحة العمل',
    'buyer.nav.tests': 'الاختبارات',

    // Buyer Tests
    'buyer.tests.title': 'الاختبارات',
    'buyer.tests.subtitle': 'عرض وتتبع اختبارات الجودة',
    'buyer.tests.testName': 'اسم الاختبار',
    'buyer.tests.status': 'الحالة',
    'buyer.tests.score': 'الدرجة',
    'buyer.tests.duration': 'المدة',
    'buyer.tests.date': 'التاريخ',
    'buyer.tests.passed': 'ناجح',
    'buyer.tests.pending': 'قيد الانتظار',
    'buyer.tests.failed': 'راسب',

    // Buyer Home
    'buyer.home.title': 'السوق الصناعي',
    'buyer.home.subtitle': 'احصل على قطع الغيار والمعدات من موردين موثوقين حول العالم',
    'buyer.home.searchPlaceholder': 'البحث برقم القطعة أو الشركة المصنعة أو كلمة مفتاحية...',
    'buyer.home.requestQuote': 'طلب سعر',
    'buyer.home.browseCatalog': 'تصفح الكتالوج',
    'buyer.home.viewOrders': 'عرض الطلبات',

    // Buyer Marketplace
    'buyer.marketplace.title': 'السوق',
    'buyer.marketplace.subtitle': 'تصفح قطع الغيار والمعدات من موردين موثوقين',
    'buyer.marketplace.searchPlaceholder': 'البحث برقم القطعة أو الشركة المصنعة...',
    'buyer.marketplace.machinery': 'الآلات',
    'buyer.marketplace.spareParts': 'قطع الغيار',
    'buyer.marketplace.electronics': 'الإلكترونيات',
    'buyer.marketplace.hydraulics': 'الهيدروليك',
    'buyer.marketplace.safetyEquipment': 'معدات السلامة',

    // Buyer Request Quote
    'buyer.rfq.title': 'طلب سعر',
    'buyer.rfq.subtitle': 'احصل على أسعار تنافسية من موردين موثوقين',
    'buyer.rfq.selectType': 'اختر النوع',
    'buyer.rfq.partDetails': 'تفاصيل القطعة',
    'buyer.rfq.reviewSubmit': 'مراجعة وإرسال',
    'buyer.rfq.whatType': 'ما نوع طلب السعر الذي تحتاجه؟',
    'buyer.rfq.singlePart': 'قطعة واحدة',
    'buyer.rfq.singlePartDesc': 'طلب سعر لقطعة واحدة محددة',
    'buyer.rfq.multipleParts': 'قطع متعددة',
    'buyer.rfq.multiplePartsDesc': 'طلب أسعار لعدة قطع',
    'buyer.rfq.enterDetails': 'أدخل تفاصيل القطعة',
    'buyer.rfq.partNumber': 'رقم القطعة',
    'buyer.rfq.manufacturer': 'الشركة المصنعة',
    'buyer.rfq.quantity': 'الكمية',
    'buyer.rfq.description': 'الوصف (اختياري)',
    'buyer.rfq.reviewRfq': 'مراجعة طلبك',
    'buyer.rfq.willBeSent': 'سيتم إرسال طلبك إلى الموردين المطابقين',
    'buyer.rfq.type': 'النوع',
    'buyer.rfq.submitRfq': 'إرسال الطلب',

    // Buyer My RFQs
    'buyer.myRfqs.title': 'طلباتي',
    'buyer.myRfqs.subtitle': 'تتبع وإدارة طلبات الأسعار',
    'buyer.myRfqs.newRfq': 'طلب جديد',
    'buyer.myRfqs.noRfqs': 'لا توجد طلبات بعد',
    'buyer.myRfqs.noRfqsDesc': 'أنشئ أول طلب سعر للحصول على أسعار تنافسية من الموردين',
    'buyer.myRfqs.createRfq': 'إنشاء طلب',
    'buyer.myRfqs.partNumber': 'رقم القطعة',
    'buyer.myRfqs.manufacturer': 'الشركة المصنعة',
    'buyer.myRfqs.qty': 'الكمية',
    'buyer.myRfqs.status': 'الحالة',
    'buyer.myRfqs.quotes': 'العروض',
    'buyer.myRfqs.created': 'تاريخ الإنشاء',
    'buyer.myRfqs.viewDetails': 'عرض التفاصيل',
    'buyer.myRfqs.pending': 'قيد الانتظار',
    'buyer.myRfqs.quoted': 'تم التسعير',
    'buyer.myRfqs.accepted': 'مقبول',
    'buyer.myRfqs.expired': 'منتهي',

    // Buyer Orders
    'buyer.orders.title': 'طلباتي',
    'buyer.orders.subtitle': 'عرض وتتبع طلبات الشراء',
    'buyer.orders.noOrders': 'لا توجد طلبات بعد',
    'buyer.orders.noOrdersDesc': 'ستظهر طلباتك هنا بعد قبول عرض سعر',
    'buyer.orders.browseMarketplace': 'تصفح السوق',
    'buyer.orders.orderNumber': 'رقم الطلب',
    'buyer.orders.supplier': 'المورد',
    'buyer.orders.items': 'المنتجات',
    'buyer.orders.total': 'الإجمالي',
    'buyer.orders.status': 'الحالة',
    'buyer.orders.date': 'التاريخ',
    'buyer.orders.processing': 'قيد المعالجة',
    'buyer.orders.shipped': 'تم الشحن',
    'buyer.orders.delivered': 'تم التوصيل',
    'buyer.orders.cancelled': 'ملغي',

    // Buyer Tracking
    'buyer.tracking.title': 'تتبع الطلب',
    'buyer.tracking.subtitle': 'تتبع شحناتك في الوقت الفعلي',
    'buyer.tracking.enterTracking': 'أدخل رقم التتبع',
    'buyer.tracking.trackingPlaceholder': 'مثال: NABD-2024-001234',
    'buyer.tracking.orderStatus': 'حالة الطلب',
    'buyer.tracking.tracking': 'التتبع',
    'buyer.tracking.inTransit': 'في الطريق',
    'buyer.tracking.orderConfirmed': 'تم تأكيد الطلب',
    'buyer.tracking.orderConfirmedDesc': 'تم تأكيد طلبك',
    'buyer.tracking.shipped': 'تم الشحن',
    'buyer.tracking.shippedDesc': 'تم استلام الشحنة من الناقل',
    'buyer.tracking.inTransitDesc': 'الشحنة في الطريق',
    'buyer.tracking.outForDelivery': 'جاري التوصيل',
    'buyer.tracking.outForDeliveryDesc': 'سيتم توصيل الشحنة اليوم',
    'buyer.tracking.delivered': 'تم التوصيل',
    'buyer.tracking.deliveredDesc': 'تم توصيل الشحنة',
    'buyer.tracking.estimated': 'المتوقع',

    // Buyer Workspace
    'buyer.workspace.title': 'مساحة العمل',
    'buyer.workspace.subtitle': 'إدارة عمليات الشراء',
    'buyer.workspace.dashboard': 'لوحة التحكم',
    'buyer.workspace.purchases': 'المشتريات',
    'buyer.workspace.suppliers': 'الموردين',
    'buyer.workspace.inventory': 'المخزون',
    'buyer.workspace.expenses': 'المصروفات',
    'buyer.workspace.totalSpend': 'إجمالي الإنفاق',
    'buyer.workspace.activeOrders': 'الطلبات النشطة',
    'buyer.workspace.pendingRfqs': 'طلبات الأسعار المعلقة',
    'buyer.workspace.suppliersCount': 'الموردين',
    'buyer.workspace.spendingOverview': 'نظرة عامة على الإنفاق',
  },
};

interface PortalProviderProps {
  children: ReactNode;
}

export const PortalProvider: React.FC<PortalProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('portal-language');
    return (saved as Language) || 'en';
  });

  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('portal-theme');
    return (saved as Theme) || 'light';
  });

  const [sidebarCollapsed, setSidebarCollapsedState] = useState<boolean>(() => {
    const saved = localStorage.getItem('portal-sidebar-collapsed');
    return saved === 'true';
  });

  const [sidebarWidth, setSidebarWidthState] = useState<number>(() => {
    const saved = localStorage.getItem('portal-sidebar-width');
    return saved ? parseInt(saved, 10) : 224;
  });

  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr';

  const setSidebarCollapsed = (collapsed: boolean) => {
    setSidebarCollapsedState(collapsed);
    localStorage.setItem('portal-sidebar-collapsed', String(collapsed));
  };

  const toggleSidebar = () => {
    setSidebarCollapsed(!sidebarCollapsed);
  };

  const setSidebarWidth = (width: number) => {
    setSidebarWidthState(width);
    localStorage.setItem('portal-sidebar-width', String(width));
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('portal-language', lang);
  };

  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    localStorage.setItem('portal-theme', newTheme);
  };

  const toggleTheme = () => {
    setTheme(theme === 'light' ? 'dark' : 'light');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Compute styles based on theme and language using smart theme getter
  const styles: ThemeStyles = useMemo(() => {
    return getThemeStyles(theme, language);
  }, [theme, language]);

  // Apply direction and theme to document
  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;

    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [direction, language, theme]);

  return (
    <PortalContext.Provider
      value={{
        language,
        setLanguage,
        theme,
        setTheme,
        toggleTheme,
        direction,
        t,
        styles,
        sidebarCollapsed,
        setSidebarCollapsed,
        toggleSidebar,
        sidebarWidth,
        setSidebarWidth,
      }}
    >
      {children}
    </PortalContext.Provider>
  );
};

export const usePortal = (): PortalContextType => {
  const context = useContext(PortalContext);
  if (!context) {
    throw new Error('usePortal must be used within a PortalProvider');
  }
  return context;
};

export default PortalContext;
